/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/butterfly-dragonfly-r-fuliginosa-b8b1543c32964c49943bb1d8ac1db9b2
title: チョウトンボ Butterfly Dragonfly, R. fuliginosa
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/dragonfly.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[3.76, -0.01, -0.01]} rotation={[0.38, 1.57, -1.95]} scale={0.42}>
            {/* <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} /> */}
          </group>
          <group position={[0.02, 0, 0.06]} rotation={[1.12, 0.02, -1.62]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials["QS1302-W07-1all-1"]} />
            <mesh geometry={nodes.Object_7.geometry} material={materials["QS1302-W07-1all-1"]} />
            <mesh geometry={nodes.Object_8.geometry} material={materials["QS1302-W07-1all-1"]} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/dragonfly.gltf");
