/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Cristianolop (https://sketchfab.com/Cristianolop)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/delorean-highpoly-18ecd0636aaa4373a903b76f9050c291
title: Delorean (highpoly)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/delorean-high.gltf')
  return (
    <group {...props} dispose={null} scale={0.5}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.99, 0.15, -1.78]} rotation={[-1.76, 1.49, -1.54]} scale={[0.08, 0.04, 0.09]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
          </group>
          <group position={[1.99, -0.2, 4.65]} scale={[0.03, 0.01, 0.04]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Material} />
          </group>
          <group position={[2.11, -0.37, -1.66]} rotation={[2.86, 0, 0]} scale={[0.05, 0.09, 0.05]}>
            <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} />
          </group>
          <group scale={[0.01, 0, 0.01]}>
            <mesh geometry={nodes.Object_11.geometry} material={materials.Cromado} />
          </group>
          <group position={[1.56, -0.05, 4.8]}>
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.013']} />
          </group>
          <group position={[1.12, -0.05, 4.8]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.013']} />
          </group>
          <group position={[-1.13, -0.05, 4.8]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.013']} />
          </group>
          <group position={[-1.57, -0.05, 4.8]}>
            <mesh geometry={nodes.Object_19.geometry} material={materials['Material.013']} />
          </group>
          <group position={[2.2, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_21.geometry} material={materials['Material.006']} />
          </group>
          <group position={[2.2, 0.12, 0.01]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_23.geometry} material={materials['Material.004']} />
          </group>
          <group position={[2.2, 0.13, -0.03]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_25.geometry} material={materials['Material.005']} />
          </group>
          <group position={[2.2, 0.13, -0.01]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_27.geometry} material={materials['Material.003']} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_29.geometry} material={materials.Brushed_Metal} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_31.geometry} material={materials.Brushed_Metal} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_34.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Object_35.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Object_36.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0, 4.1]}>
            <mesh geometry={nodes.Object_38.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0, 3.64]}>
            <mesh geometry={nodes.Object_40.geometry} material={materials.RearLight} />
          </group>
          <group position={[0, -0.04, 5.14]} rotation={[1.27, 0, 0]} scale={0.08}>
            <mesh geometry={nodes.Object_42.geometry} material={materials.material} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_44.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_46.geometry} material={materials.Brushed_Metal} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_48.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_50.geometry} material={materials.RearLightOrange} />
            <mesh geometry={nodes.Object_51.geometry} material={materials.RearLightRed} />
            <mesh geometry={nodes.Object_52.geometry} material={materials.RearLightWhite} />
            <mesh geometry={nodes.Object_53.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_55.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Object_56.geometry} material={materials.LightSide2} />
          </group>
          <group position={[0, -0.03, 1.77]}>
            <mesh geometry={nodes.Object_58.geometry} material={materials.Interior} />
          </group>
          <group position={[0.08, -0.04, -4.52]}>
            <mesh geometry={nodes.Object_60.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Object_61.geometry} material={materials.SideLight} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_63.geometry} material={materials.Interior} />
          </group>
          <mesh geometry={nodes.Object_65.geometry} material={materials.Interior} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.Espelho} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.Interior} />
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_70.geometry} material={materials.Glass01} />
          </group>
          <group position={[0, 0.73, -0.35]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_72.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_74.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Object_75.geometry} material={materials.Glass01} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_77.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Object_78.geometry} material={materials.Material} />
          </group>
          <group position={[-1.88, -0.97, 3.06]} rotation={[-Math.PI, -0.3, -Math.PI / 2]} scale={0.47}>
            <mesh geometry={nodes.Object_80.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_81.geometry} material={materials.material} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_83.geometry} material={materials.Interior} />
          </group>
          <group rotation={[Math.PI / 2, 0.09, -Math.PI / 2]} scale={0.06}>
            <mesh geometry={nodes.Object_85.geometry} material={materials.Interior} />
          </group>
          <group rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_87.geometry} material={materials.Cromado} />
          </group>
          <group rotation={[0, -Math.PI / 2, 0]} scale={1.09}>
            <mesh geometry={nodes.Object_89.geometry} material={materials.Cromado} />
          </group>
          <group rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Object_91.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.71, -3.94]} scale={[0.5, 0.54, 0.5]}>
            <mesh geometry={nodes.Object_93.geometry} material={materials.Fusao} />
            <mesh geometry={nodes.Object_94.geometry} material={materials.Fusao} />
            <mesh geometry={nodes.Object_95.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_96.geometry} material={materials['Material.009']} />
          </group>
          <group position={[0, 0.04, -3.93]}>
            <mesh geometry={nodes.Object_98.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.5, -2.97]} scale={[0.28, 0.29, 0.28]}>
            <mesh geometry={nodes.Object_100.geometry} material={materials.Mr_Fusion} />
            <mesh geometry={nodes.Object_101.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.5, -2.97]} scale={[0.28, 0.29, 0.28]}>
            <mesh geometry={nodes.Object_103.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.52, -2.97]} scale={0.95}>
            <mesh geometry={nodes.Object_105.geometry} material={materials.Mr_Fusion} />
          </group>
          <mesh geometry={nodes.Object_107.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Object_109.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Object_110.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.Interior} />
          <mesh geometry={nodes.Object_112.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Object_113.geometry} material={materials['Material.012']} />
          <group position={[0, -0.93, -2.97]}>
            <mesh geometry={nodes.Object_115.geometry} material={materials['Material.011']} />
          </group>
          <group position={[0, -0.52, -2.97]}>
            <mesh geometry={nodes.Object_117.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_118.geometry} material={materials.material} />
          </group>
          <group position={[0, 0.04, -3.93]}>
            <mesh geometry={nodes.Object_120.geometry} material={materials.Cromado} />
            <mesh geometry={nodes.Object_121.geometry} material={materials.Interior} />
          </group>
          <group position={[0, -0.16, -3.93]}>
            <mesh geometry={nodes.Object_123.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Object_124.geometry} material={materials.Cromado} />
          </group>
          <group position={[0.88, 0.5, -2.34]} scale={0.21}>
            <mesh geometry={nodes.Object_126.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.5, -2.97]}>
            <mesh geometry={nodes.Object_128.geometry} material={materials.material} />
          </group>
          <group position={[0, 0.5, -2.97]}>
            <mesh geometry={nodes.Object_130.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_131.geometry} material={materials.Material} />
          </group>
          <group position={[0, 0.5, -2.97]} scale={[0.65, 1, 1]}>
            <mesh geometry={nodes.Object_133.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.5, -2.97]} rotation={[0.72, 0.28, -1.3]} scale={[0.65, 1, 1]}>
            <mesh geometry={nodes.Object_135.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.5, -2.97]} rotation={[0.71, 0.3, -1.45]} scale={[0.65, 1, 1]}>
            <mesh geometry={nodes.Object_137.geometry} material={materials.Interior} />
          </group>
          <group position={[2.13, -0.69, -4.75]} rotation={[0.7, 0.4, -1.44]} scale={[0.65, 1, 1]}>
            <mesh geometry={nodes.Object_139.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.5, -2.97]}>
            <mesh geometry={nodes.Object_141.geometry} material={materials.Cromado} />
            <mesh geometry={nodes.Object_142.geometry} material={materials.Interior} />
          </group>
          <group position={[0, 0.5, -2.97]}>
            <mesh geometry={nodes.Object_144.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Object_145.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0, 0.32, -2.93]}>
            <mesh geometry={nodes.Object_147.geometry} material={materials.Mr_Fusion} />
          </group>
          <group position={[0, 0.5, -2.97]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 1.23, 0.08]}>
            <mesh geometry={nodes.Object_149.geometry} material={materials.material} />
          </group>
          <group position={[0, 0.5, -2.97]}>
            <mesh geometry={nodes.Object_151.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_152.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Object_153.geometry} material={materials.Interior} />
          </group>
          <group position={[0, -0.37, 5.35]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.13]}>
            <mesh geometry={nodes.Object_155.geometry} material={materials.material} />
          </group>
          <group position={[0, -0.37, 5.35]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.13]}>
            <mesh geometry={nodes.Object_157.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_158.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_159.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_160.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_161.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_162.geometry} material={materials.Material} />
          </group>
          <group rotation={[0, 0, -Math.PI]} scale={[-0.03, 0.02, 0.03]}>
            <mesh geometry={nodes.Object_164.geometry} material={materials.Interior} />
          </group>
          <group scale={0.13}>
            <mesh geometry={nodes.Object_166.geometry} material={materials.Interior} />
          </group>
          <group position={[1.41, 0.44, 1.64]} rotation={[0.72, -0.03, 0]} scale={1.68}>
            <group position={[-0.19, 0.05, 0]} rotation={[0, 0, 0.11]}>
              <group position={[-0.4, 0.02, -0.02]} rotation={[1.57, -0.12, -0.05]} scale={[0.32, 0.39, 0.13]}>
                <group position={[0, 0.02, 0.02]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.01, 0.02, 0.03]}>
                  <mesh geometry={nodes.Object_174.geometry} material={materials.material_0} />
                </group>
                <mesh geometry={nodes.Object_172.geometry} material={materials.Limpador} />
              </group>
              <mesh geometry={nodes.Object_170.geometry} material={materials.Limpador} />
            </group>
            <mesh geometry={nodes.Object_168.geometry} material={materials.Limpador} />
          </group>
          <group position={[-0.07, 0.45, 1.69]} rotation={[0.72, -0.09, 0]} scale={1.68}>
            <group position={[-0.19, 0.05, 0]} rotation={[0, 0, 0.19]}>
              <group position={[-0.4, 0.02, -0.02]} rotation={[1.57, -0.14, -0.04]} scale={[0.32, 0.39, 0.13]}>
                <mesh geometry={nodes.Object_180.geometry} material={materials.Limpador} />
              </group>
              <mesh geometry={nodes.Object_178.geometry} material={materials.Limpador} />
            </group>
            <mesh geometry={nodes.Object_176.geometry} material={materials.Limpador} />
          </group>
          <group position={[1.94, -0.88, -3.04]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={0.52}>
            <mesh geometry={nodes.Object_182.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_183.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_184.geometry} material={materials.material} />
          </group>
          <group position={[1.94, -0.88, -3.04]} scale={[0.97, 0.82, 0.82]}>
            <mesh geometry={nodes.Object_186.geometry} material={materials.Tyres} />
          </group>
          <group position={[0, 0, 4.13]}>
            <mesh geometry={nodes.Object_188.geometry} material={materials.Vidro} />
          </group>
          <group position={[0, 0, 4.32]}>
            <mesh geometry={nodes.Object_190.geometry} material={materials.Placa} />
          </group>
          <group position={[1.86, -0.97, 3.06]} rotation={[0, 0.3, 0]} scale={[0.88, 0.74, 0.74]}>
            <mesh geometry={nodes.Object_192.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1.86, -0.97, 3.06]} rotation={[-Math.PI, -0.3, -Math.PI / 2]} scale={0.47}>
            <mesh geometry={nodes.Object_194.geometry} material={materials.material} />
          </group>
          <group position={[-1.78, -0.97, 3.06]} rotation={[0, 0.3, 0]} scale={[0.88, 0.74, 0.74]}>
            <mesh geometry={nodes.Object_196.geometry} material={materials['Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/delorean-high.gltf')
