/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Spinnee (https://sketchfab.com/Spinnee)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/four-horsemen-24-pestilence-and-famine-f94feba7587543e48babc21d1afa0422
title: Four Horsemen (2/4): Pestilence and Famine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Horsemen2(props) {
  const { nodes, materials } = useGLTF('/horsemen2.gltf')
  return (
    <group {...props} dispose={null} scale={15}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <group position={[-8.78, -8.99, 0.65]} scale={[1.61, 0.97, 1.61]}>
            <mesh geometry={nodes.Gas_Gas_Mat_0.geometry} material={materials.Gas_Mat} />
          </group>
          <group position={[0, 0.79, 0]} scale={0.31}>
            <group position={[-7.4, -6.18, 4.14]}>
              <group position={[-0.5, -1.33, 7]} rotation={[0.08, 0.07, -0.13]}>
                <group position={[-0.85, 0.17, 1.07]} rotation={[1.33, -0.8, -1.9]} scale={[0.15, 1.43, 0.15]}>
                  <mesh geometry={nodes.pCylinder1_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-2.44, -0.49, 1.44]} rotation={[0.86, -1.23, -2.32]} scale={[-0.23, 0.16, 0.48]}>
                  <mesh geometry={nodes.pCube1_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-1.23, 0.81, -2.69]} rotation={[2.85, 1.41, -2.57]} scale={[0.09, 1.32, 0.09]}>
                  <mesh geometry={nodes.pCylinder3_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-0.73, 0.52, -1.11]} rotation={[2.38, -0.22, -0.21]} scale={[0.21, 2, 0.21]}>
                  <mesh geometry={nodes.pCylinder4_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-1.42, -0.41, -3.3]} rotation={[2.87, -0.3, -0.08]} scale={[-0.32, 0.23, 0.68]}>
                  <mesh geometry={nodes.pCube2_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[0.36, 2.47, 0.15]}>
                  <mesh geometry={nodes.Locust_Lowpoly_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-0.52, 1.48, -0.86]} rotation={[0.4, 0.22, 1.73]} scale={[1.9, 1.9, 4.7]}>
                  <mesh geometry={nodes.pPlane10_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-1.09, 0.38, 2.98]} rotation={[3.07, -0.89, -2.91]} scale={[0.05, 0.79, 0.05]}>
                  <mesh geometry={nodes.pCylinder5_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-0.6, 0.21, 2.12]} rotation={[0.81, -0.38, -2.77]} scale={[0.13, 1.2, 0.13]}>
                  <mesh geometry={nodes.pCylinder6_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-1.29, -0.35, 3.31]} rotation={[0.29, -0.51, -3]} scale={[-0.19, 0.14, 0.4]}>
                  <mesh geometry={nodes.pCube3_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
                <group position={[-2, 0.38, 1.33]} rotation={[3.1, -0.08, -2.85]} scale={[0.06, 0.94, 0.06]}>
                  <mesh geometry={nodes.pCylinder2_Other_Mat1_0_4.geometry} material={materials.Other_Mat1} />
                </group>
              </group>
            </group>
            <group position={[-4.27, -19.89, -0.66]} rotation={[-0.15, 0.89, -0.86]} scale={0.68}>
              <group position={[-2.36, 13.98, 1.18]} rotation={[3.1, -0.08, -2.85]} scale={[0.06, 0.94, 0.06]}>
                <mesh geometry={nodes.pCylinder2_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.65, 13.26, 3.16]} rotation={[0.29, -0.51, -3]} scale={[-0.19, 0.14, 0.4]}>
                <mesh geometry={nodes.pCube3_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-0.96, 13.81, 1.97]} rotation={[0.81, -0.38, -2.77]} scale={[0.13, 1.2, 0.13]}>
                <mesh geometry={nodes.pCylinder6_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.46, 13.99, 2.83]} rotation={[3.07, -0.89, -2.91]} scale={[0.05, 0.79, 0.05]}>
                <mesh geometry={nodes.pCylinder5_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-0.79, 15.11, -1.03]} rotation={[0.4, 0.22, 1.73]} scale={[1.9, 1.9, 4.7]}>
                <mesh geometry={nodes.pPlane10_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0, 76.48, 0]}>
                <mesh geometry={nodes.Locust_Lowpoly_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.78, 13.2, -3.45]} rotation={[2.87, -0.3, -0.08]} scale={[-0.32, 0.23, 0.68]}>
                <mesh geometry={nodes.pCube2_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.09, 14.13, -1.26]} rotation={[2.38, -0.22, -0.21]} scale={[0.21, 2, 0.21]}>
                <mesh geometry={nodes.pCylinder4_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.59, 14.42, -2.84]} rotation={[2.85, 1.41, -2.57]} scale={[0.09, 1.32, 0.09]}>
                <mesh geometry={nodes.pCylinder3_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-2.81, 13.11, 1.28]} rotation={[0.86, -1.23, -2.32]} scale={[-0.23, 0.16, 0.48]}>
                <mesh geometry={nodes.pCube1_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.21, 13.78, 0.91]} rotation={[1.33, -0.8, -1.9]} scale={[0.15, 1.43, 0.15]}>
                <mesh geometry={nodes.pCylinder1_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
              </group>
            </group>
            <group position={[-23.14, -22.21, -8.1]} rotation={[-0.32, -0.93, -0.52]} scale={0.68}>
              <group position={[-2.36, 13.98, 1.18]} rotation={[3.1, -0.08, -2.85]} scale={[0.06, 0.94, 0.06]}>
                <mesh geometry={nodes.pCylinder2_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.65, 13.26, 3.16]} rotation={[0.29, -0.51, -3]} scale={[-0.19, 0.14, 0.4]}>
                <mesh geometry={nodes.pCube3_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-0.96, 13.81, 1.97]} rotation={[0.81, -0.38, -2.77]} scale={[0.13, 1.2, 0.13]}>
                <mesh geometry={nodes.pCylinder6_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.46, 13.99, 2.83]} rotation={[3.07, -0.89, -2.91]} scale={[0.05, 0.79, 0.05]}>
                <mesh geometry={nodes.pCylinder5_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-0.79, 15.11, -1.03]} rotation={[0.4, 0.22, 1.73]} scale={[1.9, 1.9, 4.7]}>
                <mesh geometry={nodes.pPlane10_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0, 76.48, 0]}>
                <mesh geometry={nodes.Locust_Lowpoly_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.78, 13.2, -3.45]} rotation={[2.87, -0.3, -0.08]} scale={[-0.32, 0.23, 0.68]}>
                <mesh geometry={nodes.pCube2_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.09, 14.13, -1.26]} rotation={[2.38, -0.22, -0.21]} scale={[0.21, 2, 0.21]}>
                <mesh geometry={nodes.pCylinder4_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.59, 14.42, -2.84]} rotation={[2.85, 1.41, -2.57]} scale={[0.09, 1.32, 0.09]}>
                <mesh geometry={nodes.pCylinder3_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-2.81, 13.11, 1.28]} rotation={[0.86, -1.23, -2.32]} scale={[-0.23, 0.16, 0.48]}>
                <mesh geometry={nodes.pCube1_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-1.21, 13.78, 0.91]} rotation={[1.33, -0.8, -1.9]} scale={[0.15, 1.43, 0.15]}>
                <mesh geometry={nodes.pCylinder1_Other_Mat1_0_1.geometry} material={materials.Other_Mat1} />
              </group>
            </group>
            <group position={[4.78, 18.45, 2.41]} rotation={[0.42, 0.24, -0.41]}>
              <group position={[44.49, -4.88, -41.43]} rotation={[3.1, -0.08, -2.85]} scale={[0.06, 0.94, 0.06]}>
                <mesh geometry={nodes.pCylinder2_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[45.2, -5.61, -39.45]} rotation={[0.29, -0.51, -3]} scale={[-0.19, 0.14, 0.4]}>
                <mesh geometry={nodes.pCube3_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[45.89, -5.05, -40.64]} rotation={[0.81, -0.38, -2.77]} scale={[0.13, 1.2, 0.13]}>
                <mesh geometry={nodes.pCylinder6_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[45.39, -4.88, -39.79]} rotation={[3.07, -0.89, -2.91]} scale={[0.05, 0.79, 0.05]}>
                <mesh geometry={nodes.pCylinder5_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[46.06, -3.75, -43.65]} rotation={[0.4, 0.22, 1.73]} scale={[1.9, 1.9, 4.7]}>
                <mesh geometry={nodes.pPlane10_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[46.85, 57.62, -42.61]}>
                <mesh geometry={nodes.Locust_Lowpoly_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[45.07, -5.67, -46.07]} rotation={[2.87, -0.3, -0.08]} scale={[-0.32, 0.23, 0.68]}>
                <mesh geometry={nodes.pCube2_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[45.76, -4.74, -43.87]} rotation={[2.38, -0.22, -0.21]} scale={[0.21, 2, 0.21]}>
                <mesh geometry={nodes.pCylinder4_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[45.26, -4.45, -45.45]} rotation={[2.85, 1.41, -2.57]} scale={[0.09, 1.32, 0.09]}>
                <mesh geometry={nodes.pCylinder3_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[44.04, -5.75, -41.33]} rotation={[0.86, -1.23, -2.32]} scale={[-0.23, 0.16, 0.48]}>
                <mesh geometry={nodes.pCube1_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[45.64, -5.09, -41.7]} rotation={[1.33, -0.8, -1.9]} scale={[0.15, 1.43, 0.15]}>
                <mesh geometry={nodes.pCylinder1_Other_Mat1_0_2.geometry} material={materials.Other_Mat1} />
              </group>
            </group>
            <group position={[-15.19, 0.94, -41.23]} rotation={[0.6, 0.28, 0.4]}>
              <group position={[-0.53, 5.14, 2.97]} rotation={[3.1, -0.08, -2.85]} scale={[0.06, 0.94, 0.06]}>
                <mesh geometry={nodes.pCylinder2_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0.18, 4.42, 4.95]} rotation={[0.29, -0.51, -3]} scale={[-0.19, 0.14, 0.4]}>
                <mesh geometry={nodes.pCube3_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0.87, 4.97, 3.76]} rotation={[0.81, -0.38, -2.77]} scale={[0.13, 1.2, 0.13]}>
                <mesh geometry={nodes.pCylinder6_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0.38, 5.15, 4.62]} rotation={[3.07, -0.89, -2.91]} scale={[0.05, 0.79, 0.05]}>
                <mesh geometry={nodes.pCylinder5_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[1.04, 6.27, 0.76]} rotation={[0.4, 0.22, 1.73]} scale={[1.9, 1.9, 4.7]}>
                <mesh geometry={nodes.pPlane10_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[1.84, 67.64, 1.79]}>
                <mesh geometry={nodes.Locust_Lowpoly_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0.05, 4.36, -1.66]} rotation={[2.87, -0.3, -0.08]} scale={[-0.32, 0.23, 0.68]}>
                <mesh geometry={nodes.pCube2_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0.74, 5.29, 0.53]} rotation={[2.38, -0.22, -0.21]} scale={[0.21, 2, 0.21]}>
                <mesh geometry={nodes.pCylinder4_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0.24, 5.58, -1.05]} rotation={[2.85, 1.41, -2.57]} scale={[0.09, 1.32, 0.09]}>
                <mesh geometry={nodes.pCylinder3_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[-0.97, 4.27, 3.08]} rotation={[0.86, -1.23, -2.32]} scale={[-0.23, 0.16, 0.48]}>
                <mesh geometry={nodes.pCube1_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
              <group position={[0.62, 4.94, 2.71]} rotation={[1.33, -0.8, -1.9]} scale={[0.15, 1.43, 0.15]}>
                <mesh geometry={nodes.pCylinder1_Other_Mat1_0_3.geometry} material={materials.Other_Mat1} />
              </group>
            </group>
          </group>
          <group position={[-8.77, -17.26, 0.67]}>
            <group position={[0, 10.02, -1.38]} rotation={[0.76, 0, 0]} scale={[0.11, 2.04, 0.11]}>
              <mesh geometry={nodes.IncenseRope1_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
            </group>
            <group position={[0, 3.8, 0]}>
              <mesh geometry={nodes.Inscense_1_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
            </group>
            <group position={[0, 13.16, 0]} scale={[0.15, 2.63, 0.15]}>
              <mesh geometry={nodes.IncenseRope_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
            </group>
            <group position={[-1.35, 9.98, 0.02]} rotation={[1.58, 0.82, -1.57]} scale={[0.11, 2.04, 0.11]}>
              <mesh geometry={nodes.IncenseRope4_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
            </group>
            <group position={[0, 10.03, 1.44]} rotation={[2.33, 0.03, 3.14]} scale={[0.11, 2.04, 0.11]}>
              <mesh geometry={nodes.IncenseRope2_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
            </group>
            <group position={[1.47, 10.03, 0.01]} rotation={[1.62, -0.75, 1.59]} scale={[0.11, 2.04, 0.11]}>
              <mesh geometry={nodes.IncenseRope3_Other_Mat1_0.geometry} material={materials.Other_Mat1} />
            </group>
          </group>
          <group position={[-0.1, -0.24, -0.09]}>
            <mesh geometry={nodes.FrontDrapes_Pestilence_Mat_0.geometry} material={materials.Pestilence_Mat} />
          </group>
          <mesh geometry={nodes.SideDrapes_Pestilence_Mat_0.geometry} material={materials.Pestilence_Mat} />
          <group position={[-1.23, -1.26, 1.44]} rotation={[0.39, -0.39, 0.14]}>
            <mesh geometry={nodes.BackDrape_Pestilence_Mat_0.geometry} material={materials.Pestilence_Mat} />
          </group>
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Pestilence_Mat} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Pestilence_Mat} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Pestilence_Mat} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Pestilence_Mat} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Pestilence_Mat} skeleton={nodes.Object_15.skeleton} />
          <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Pestilence_Mat} skeleton={nodes.Object_17.skeleton} />
          <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Pestilence_Mat} skeleton={nodes.Object_19.skeleton} />
          <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_21.skeleton} />
          <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_23.skeleton} />
          <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_25.skeleton} />
          <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_27.skeleton} />
          <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_29.skeleton} />
          <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_31.skeleton} />
          <skinnedMesh geometry={nodes.Object_33.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_33.skeleton} />
          <skinnedMesh geometry={nodes.Object_35.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_35.skeleton} />
          <skinnedMesh geometry={nodes.Object_37.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_37.skeleton} />
          <skinnedMesh geometry={nodes.Object_39.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_39.skeleton} />
          <skinnedMesh geometry={nodes.Object_41.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_41.skeleton} />
          <skinnedMesh geometry={nodes.Object_43.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_43.skeleton} />
          <skinnedMesh geometry={nodes.Object_45.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_45.skeleton} />
          <skinnedMesh geometry={nodes.Object_47.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_47.skeleton} />
          <skinnedMesh geometry={nodes.Object_49.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_49.skeleton} />
          <skinnedMesh geometry={nodes.Object_51.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_51.skeleton} />
          <skinnedMesh geometry={nodes.Object_53.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_53.skeleton} />
          <skinnedMesh geometry={nodes.Object_55.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_55.skeleton} />
          <skinnedMesh geometry={nodes.Object_57.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_57.skeleton} />
          <skinnedMesh geometry={nodes.Object_59.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_59.skeleton} />
          <skinnedMesh geometry={nodes.Object_61.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_61.skeleton} />
          <skinnedMesh geometry={nodes.Object_63.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_63.skeleton} />
          <skinnedMesh geometry={nodes.Object_65.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_65.skeleton} />
          <skinnedMesh geometry={nodes.Object_67.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_67.skeleton} />
          <skinnedMesh geometry={nodes.Object_69.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_69.skeleton} />
          <skinnedMesh geometry={nodes.Object_71.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_71.skeleton} />
          <skinnedMesh geometry={nodes.Object_73.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_73.skeleton} />
          <skinnedMesh geometry={nodes.Object_75.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_75.skeleton} />
          <skinnedMesh geometry={nodes.Object_77.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_77.skeleton} />
          <skinnedMesh geometry={nodes.Object_79.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_79.skeleton} />
          <skinnedMesh geometry={nodes.Object_81.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_81.skeleton} />
          <skinnedMesh geometry={nodes.Object_83.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_83.skeleton} />
          <skinnedMesh geometry={nodes.Object_85.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_85.skeleton} />
          <skinnedMesh geometry={nodes.Object_87.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_87.skeleton} />
          <skinnedMesh geometry={nodes.Object_89.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_89.skeleton} />
          <skinnedMesh geometry={nodes.Object_91.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_91.skeleton} />
          <skinnedMesh geometry={nodes.Object_93.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_93.skeleton} />
          <skinnedMesh geometry={nodes.Object_95.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_95.skeleton} />
          <skinnedMesh geometry={nodes.Object_97.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_97.skeleton} />
          <skinnedMesh geometry={nodes.Object_99.geometry} material={materials.Famine_Mat} skeleton={nodes.Object_99.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/horsemen2.gltf')
