/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: eArtisan (https://sketchfab.com/LOLITAart)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/taeyeon-test-dragon-784c2221813d4edaac76797434d05578
title: Taeyeon_TEST_dragon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/taeyeon_dragon.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.43, 3.22, 10.93]} rotation={[-1.64, -0.08, -2.3]} scale={[18.26, 18.37, 18.02]}>
            <mesh geometry={nodes.Abdomen1_Skin_0.geometry} material={materials.Skin} />
            <mesh geometry={nodes.Abdomen1_Arms_0.geometry} material={materials.Arms} />
            <mesh geometry={nodes.Abdomen1_Tongue_0.geometry} material={materials.Tongue} />
            <mesh geometry={nodes.Abdomen1_Fingernails_0.geometry} material={materials.Fingernails} />
            <mesh geometry={nodes.Abdomen1_Claws_0.geometry} material={materials.Claws} />
            <mesh geometry={nodes.Abdomen1_SkinWing_0.geometry} material={materials.SkinWing} />
            <mesh geometry={nodes.Abdomen1_WingMembrane_0.geometry} material={materials.WingMembrane} />
            <mesh geometry={nodes.Abdomen1_Sclera_0.geometry} material={materials.Sclera} />
            <mesh geometry={nodes.Abdomen1_Cornea_0.geometry} material={materials.Cornea} />
            <mesh geometry={nodes.Abdomen1_Pupils_0.geometry} material={materials.Pupils} />
            <mesh geometry={nodes.Abdomen1_Irises_0.geometry} material={materials.Irises} />
            <mesh geometry={nodes.Abdomen1_EyeMoisture_0.geometry} material={materials.EyeMoisture} />
            <mesh geometry={nodes.Abdomen1_Sclera_DAZ_Dragon_3_0.geometry} material={materials.Sclera_DAZ_Dragon_3} />
            <mesh geometry={nodes.Abdomen1_EyeSurface_0.geometry} material={materials.EyeSurface} />
            <mesh geometry={nodes.Abdomen1_Pupil_0.geometry} material={materials.Pupil} />
            <mesh geometry={nodes.Abdomen1_Torso_0.geometry} material={materials.Torso} />
            <mesh geometry={nodes.Abdomen1_Body_Cloth_0.geometry} material={materials.Body_Cloth} />
            <mesh geometry={nodes.Abdomen1_Body_Edge_0.geometry} material={materials.Body_Edge} />
            <mesh geometry={nodes.Abdomen1_Arm_Cloth_0.geometry} material={materials.Arm_Cloth} />
            <mesh geometry={nodes.Abdomen1_Arm_Edge_0.geometry} material={materials.Arm_Edge} />
            <mesh geometry={nodes.Abdomen1_Side1_0.geometry} material={materials.Side1} />
            <mesh geometry={nodes.Abdomen1_Side2_0.geometry} material={materials.Side2} />
            <mesh geometry={nodes.Abdomen1_Back_0.geometry} material={materials.Back} />
            <mesh geometry={nodes.Abdomen1_BackUnder_0.geometry} material={materials.BackUnder} />
            <mesh geometry={nodes.Abdomen1_Front2_0.geometry} material={materials.Front2} />
            <mesh geometry={nodes.Abdomen1_Bangs2_0.geometry} material={materials.Bangs2} />
            <mesh geometry={nodes.Abdomen1_Front1_0.geometry} material={materials.Front1} />
            <mesh geometry={nodes.Abdomen1_Legs_0.geometry} material={materials.Legs} />
            <mesh geometry={nodes.Abdomen1_Thigh_Cloth_0.geometry} material={materials.Thigh_Cloth} />
            <mesh geometry={nodes.Abdomen1_Thigh_Edge_0.geometry} material={materials.Thigh_Edge} />
            <mesh geometry={nodes.Abdomen1_WingClaws_0.geometry} material={materials.WingClaws} />
            <mesh geometry={nodes.Abdomen1_Mouth_0.geometry} material={materials.Mouth} />
            <mesh geometry={nodes.Abdomen1_Toenails_0.geometry} material={materials.Toenails} />
            <mesh geometry={nodes.Abdomen1_Bangs1_0.geometry} material={materials.Bangs1} />
            <mesh geometry={nodes.Abdomen1_Eyelashes_0.geometry} material={materials.Eyelashes} />
            <mesh geometry={nodes.Abdomen1_Face_0.geometry} material={materials.Face} />
            <mesh geometry={nodes.Abdomen1_Lips_0.geometry} material={materials.Lips} />
            <mesh geometry={nodes.Abdomen1_Ears_0.geometry} material={materials.Ears} />
            <mesh geometry={nodes.Abdomen1_EyeSocket_0.geometry} material={materials.EyeSocket} />
            <mesh geometry={nodes.Abdomen1_Cap_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Abdomen1_Earring_0.geometry} material={materials.Earring} />
            <mesh geometry={nodes.Abdomen1_Gem_0.geometry} material={materials.material_41} />
            <mesh geometry={nodes.Abdomen1_SkinHead_0.geometry} material={materials.SkinHead} />
            <mesh geometry={nodes.Abdomen1_Horns_0.geometry} material={materials.Horns} />
            <mesh geometry={nodes.Abdomen1_TeethUpper_0.geometry} material={materials.TeethUpper} />
            <mesh geometry={nodes.Abdomen1_MouthInner_0.geometry} material={materials.MouthInner} />
            <mesh geometry={nodes.Abdomen1_Thong_0.geometry} material={materials.Thong} />
            <mesh geometry={nodes.Abdomen1_Earring_Dragonia_Earring_R_0.geometry} material={materials.Earring_Dragonia_Earring_R} />
            <mesh geometry={nodes.Abdomen1_Gem_Dragonia_Earring_R_0.geometry} material={materials.Gem_Dragonia_Earring_R} />
            <mesh geometry={nodes.Abdomen1_Body_0.geometry} material={materials.Body} />
            <mesh geometry={nodes.Abdomen1_Wing_0.geometry} material={materials.Wing} />
            <mesh geometry={nodes.Abdomen1_Eyes_0.geometry} material={materials.Eyes} />
            <mesh geometry={nodes.Abdomen1_Teeth_0.geometry} material={materials.Teeth} />
            <mesh geometry={nodes.Abdomen1_Shin_Cloth_0.geometry} material={materials.Shin_Cloth} />
            <mesh geometry={nodes.Abdomen1_Shin_Edge_0.geometry} material={materials.Shin_Edge} />
            <mesh geometry={nodes.Abdomen1_TeethLower_0.geometry} material={materials.TeethLower} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/taeyeon_dragon.gltf')
